language: node_js

node_js:
- 8.11.2

branches:
  only:
  - develop

script:
- npm run test

deploy:
  provider: heroku
    api_key:
    secure: r95H1YfVc9C3nyKT5CqqpvIwvk/MDypxogN7ibYklzD/LTMSnf/gqRZ3unh/ZAd6EeOTz0rzCzIC+ExRP+fTCrH5LuOTqHwIw77pW3l3ck5ULwmlLPPj+FJDrZqpk/E5TKTr3FMJWdep3L0W2a0ITkJ5TSehijtKnGhprvnc+KxtAhN12HNusfM9QAhLeuUxAT3X5F2Y9r3mj+tssr2xBlLuki5lwA3Bj0hLgEAmtud05dPEXDcX85cZahxzQ0hgpn5Gdl4TrL/GLLR5f1TA19dzABnfcvqHIt/csmggtB6zPXYLZ/HK6s+1+d8XiN5YXr0FadKaVGntP7IXsItFBhR+5MSnxAqYYCOAGFfTi38n/xzFsA1Ri76IypsLAo2cprHeEBX8svaiIHtAvaDu+HrLAttmO9dWpWOU14k2EoGNokG29l8wXzU6tV9Ntbq28+mYBBO32uh11AdZ5tDNXiEBvLQowDFYyRuPZzcoy3LudA+XItI+qTMtANN3BRsjwP8oAOG7Xq8MRUe95Tn6Exz8WVPb6p5Tm6xZKacv5NwyXbXg+G97/fSQ07hSooxWj4dEYB7Ykf43a/E0MZbmqfAwCzCMmLI09Ua6aNKK07ym6oUqyhFsWWmDh2aTYKcFLP9Ehx8mRK8g0Dd3MLki06sNgdRgZ6Mad/OO3QgTtNs=
  app: loft-taxi-mihanizm56
  on: 
    branch: develop