language: node_js
node_js:
- 8.11.2


branches:
  only:
  - develop

script:
- npm run test

deploy:
  provider: heroku
    api_key:
      secure: dTV8ixcGDDE/RKpwSxtg0Wa0N3n3tBVm8qF+bDT6vlQhNDuv6C90gSakPJ/HArxN/HQzmAHz04IvdposKljW/6lNMFpDDPJwUiQ3BVPb7Zn4G5qNFQZY8HFzRcKSyGL2yU0Ku2gZ7Otb5O2JLwr160aMNLYF1w06Ckz1D9vxOt9wZkKek0cQSN3qKrFB6wDVhm7fxR654cJu3zFdSyJtqbYGcxsjV75y0BKIPPEunnZnQpOghNv7ioJR//P3o1LSbQvnitTQic1zX58Eg8L115r5Jh3R4JyNSYII62B+dDyNkFUL2BseErtCfoVDuOdJEJ1Qqetl09oMCTdiC71GK/MQJ+OdXaGjZ42y1Fa7mMfMeEM/i+KXh7ZXOf0itp0oRcFRLJMz7DDpF6kaQXckgqHgjXKkQ9dzXl+zlaf7rgitnh5PfjuY181RmZraom9jkcvZbMqdKVOLmmiufJpEmU9KuyuEpjZPC887QbNc9nZV4TSFjUYHkW4ZYeY1r45O9s2FtHXcyYyHf+aXUPb5eq2QzOfDKUILcJoEob2I5pxTJLPRdyAlA+Wzc11orSzgz/3OLkQCpbf3oX2v2J/+8IpDVSjJGhYBiKO/Na/QXoxhtyAjRC80cSFQuCCGsudQLgU1qYZCVK7WXOkiBoBar3sA02D8XIGfQM1Bh15vp8Q=
  app: loft-taxi-mihanizm56
  on: 
    branch: develop